nurkiewicz/polski-w-it

README.md

Per ostatnie zdanie tu: https://github.com/nurkiewicz/polski-w-it/issues/7#issuecomment-347482267

Developer - programista

---

README.md

Set - zbiór.

---

README.md

https://sjp.pwn.pl/slowniki/funkcjonalno%C5%9B%C4%87.html
https://sjp.pwn.pl/sjp/guzik;2463567.html
https://sjp.pwn.pl/poradnia/haslo/anulacja;13028.html

propozycja zmian tłumaczeń

---

README.md

słowo - 'consistent'

---

README.md

adding new words

---

README.md

Prototajp ;) Oraz PoC, które po polsku zazwyczaj występuje jako PiOłSi

Dodane dwa słowa

---

README.md

Nie można _"przenazwać"_ zmiennej, ale można zmienić jej nazwę.

rename -> zmienić nazwę

---

README.md

Aktualizacja tłumaczenia

---

README.md

share -> udostępnić

---

README.md

Bardzo trafny, ale mało znany polski odpowiednik.

credentials -> poświadczenia

---

README.md

Odmiana wg wzorca 2.1: https://pl.wiktionary.org/wiki/klient jeśli nie chodzi o ludzi.

clients -> klienty

---

README.md

Albowiem trigeruje mnie ciągłe trigerowanie w różnych flołach. ;-)

trigger -> wyzwalać

---

README.md

fix (n/v) rozdzielone

---

README.md

unlock -> odblokować

---

README.md

Dodanie słowa backup

---

README.md

Jak w tytule, tłumaczenie dla zwrotu _memory leak_.
Przykład użycia:
Zamiast: _Niektóre systemy tego samolotu wymagają restartu raz na miesiąc, pewnie mają problem z memory likami..._
Można: _Niektóre systemy tego samolotu wymagają restartu raz na miesiąc, pewnie mają problem z wyciekami pamięci..._

Memory leak -> wyciek pamięci

---

README.md

Parę nowych słów, które często padają :-)
Z pozdrowieniami :)

Few additional words

---

README.md

* add 17 new phrases (_asynchronous_, _call_, _code review_, _collaborate_, _embed_, _encapsulation_, _encryption_, _estimate_, _fail_, _guide_, _human resources (HR)_, _include_, _leader_, _remote_, _skill_, _talk_, _target_)
* add polish version of "_event_": "_iwent_", "_impact_": "_impakt_", "_meeting_": "_mityng_"
* add additional translation of "_share_"
Most of the words were added from the following talk: [SegFault Unconference, 25-26.11.2019. Piotr Przybył: "#ąęszcz"](https://www.youtube.com/watch?v=LWoy_bmEHD0).

Add 17 new phrases

---

README.md

Zamiast:
Ten field w klasie Foo może być final.
Można:
To pole w klasie Foo może mieć modyfikator final.

Field -> pole

---

README.md

Zamiast:
"Klożur" to jedno z pojęć znanych z programowania funkcyjnego.
Można:
Domknięcie to jedno z pojęć znanych z programowania funkcyjnego.

Closure -> domknięcie

---

README.md

Zamiast:
Skołp tej zmiennej jest ograniczony do tej metody.
Można:
Zasięg tej zmiennej jest ograniczony do tej metody.

Scope -> zasięg

---

test_readme.py

sortowanie duża mała litera
**przykład:** 
```
lista=["A", "X", "B", "b", "x", "C"]
lista.sort(key=str.lower)
print(lista)
lista2=["A", "X", "B", "b", "x", "C"]
lista2.sort()
print(lista2)
```
**wyjscie:**
```
['A', 'B', 'b', 'C', 'X', 'x']
['A', 'B', 'C', 'X', 'b', 'x']
```

dodawanie do słownika wyrazów z dużymi literami

---

README.adoc

bottleneck -> wąskie gardło, wąski przekrój
https://encyklopedia.pwn.pl/haslo/;3994398
https://pl.wikipedia.org/wiki/W%C4%85skie_gard%C5%82o

bottleneck

---

README.adoc

core (a) -> główny, najbardziej istotny

---

README.adoc

Pinglish: Obiekty alokowane są na heapie.
Polski: Obiekty alokowane są na stercie.
Osobiście lubię stertę (i stos), a na ostatniej Confiturze, na jednym ze stanowisk, usłyszałem: "Mów mi po angielsku, na heapie!"

heap -> sterta

---

README.adoc

dekrypcja - słyszę takie określenie zamiast deszyfracja

decryption

---

README.adoc

Zobaczone dzisiaj na slacku ;)
(nie do odzobaczenia ;))

elewacja -> elevation

---

.github/workflows/python-pytest.yml

Ten pijar fiksuje warningi od deprekejted akcji ;)
||
This PR fixes warnings from using old action versions ;)

Workflow update

---

README.adoc

Added details to the word "agents".

agents -> agents (_n_)

---

README.adoc

Added details to the word "authentication".

authentication -> authentication (_n_).

---

README.adoc

Added details to the word "asynchronous".

asynchronous -> asynchronous (_a_)

---

README.adoc

Added details to the word "asset".

asset -> asset (_n_)

---

README.adoc

Added details to the word "answer".

answer -> answer (_n_)

---

README.adoc

Added details to the word "anti-pattern".

anti-pattern -> anti-pattern (_n_)

---

README.adoc

Added details to the word "case".

case -> case (_n_)

---

README.adoc

Added details to the word "bottleneck".

bottleneck -> bottleneck (_n_)

---

README.adoc

Added details to the word "backup".

backup -> backup (_n_)

---

README.adoc

Added details to the word "approve".

approve  -> approve (_v_)

---

README.adoc

Added details to the word "authorization".

authorization -> authorization (_n_)
